#!/usr/bin/env bash
set -euo pipefail

seed_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

cue vet \
  "$seed_root/contract/registry.cue" \
  "$seed_root/contract/projection.cue" \
  "$seed_root/contract/fragments.cue" \
  "$seed_root/contract/hooks.cue" \
  "$seed_root/contract/prompt_classifier.cue" \
  "$seed_root/contract/proof.cue" \
  "$seed_root/fixtures/registry.valid.cue"

"$seed_root/scripts/generate.sh" "$tmp_dir"
diff -ru "$seed_root/generated" "$tmp_dir"

go run "$seed_root/cmd/seed-resolver/main.go" validate \
  --generated "$seed_root/generated" \
  --valid-fixture "$seed_root/fixtures/prompt_classification.valid.cue"

for fixture in "$seed_root"/fixtures/*.invalid.cue; do
  case "$(basename "$fixture")" in
    context_body_from_prompt.invalid.cue)
      expected="cannot assemble context bodies"
      ;;
    full_registry_from_prompt.invalid.cue)
      expected="cannot emit the registry"
      ;;
    mcp_tool_output_as_context.invalid.cue)
      expected="MCP/tool output cannot become implied context"
      ;;
    unknown_fragment.invalid.cue)
      expected="was not generated by turnStart"
      ;;
    *)
      echo "missing expected failure for fixture: $fixture" >&2
      exit 1
      ;;
  esac

  if output="$(go run "$seed_root/cmd/seed-resolver/main.go" validate-fixture \
    --generated "$seed_root/generated" \
    --fixture "$fixture" 2>&1)"; then
    echo "expected invalid fixture to fail: $fixture" >&2
    exit 1
  fi
  if [[ "$output" != *"$expected"* ]]; then
    echo "unexpected validation failure for $fixture: $output" >&2
    exit 1
  fi
done
